### PR TITLE
For...of polyfill

### PR DESCRIPTION
**Pull request by flore77**
Fixes the `for...of` compatibility problem on IE from https://github.com/flore77/browserstack-runner/pull/2.

### CODE REVIEW

**Comment by flore77** [comment]
I tested and now everything is functioning well now, the browserstack tests are passing now also with Mocha's runtime.

I didn't manage it to get it work neither `babel-polyfill`, I get this error:
image

But it does work if I include separately the `dist/polyfill.js` bundle.

**Comment by leobalter** [comment]
for of should not be included by polyfills, this is syntax matters and not a built-in api.

```js
var tests = this.getAllTests()
```

Does it return an array? If so, you can use forEach instead of loops.

If it's an ordinary object and you can use the polyfill for `Object.values`.

**Comment by flore77** [comment]
>  this is syntax matters and not a built-in api.

So and so because `for...of` is compiled by babel with help of `Symbol.iterator`, which is an ES6 feature, so it should be part of the built-in api, but unfortunately is not available in IE and is resulting into this:

image
 
> Does it return an array?
Yes.

>  you can use forEach instead of loops.

Yes, of course, but I don't like that I am not able to use this ES6 feature. And this is not the only place where we are using it and I thought it would be easier to include a polyfill, but I didn't manage to sort it yet.

**Comment by flore77** [comment]
This, https://phabricator.babeljs.io/T7348, is the same error I get when I'm importing `babel-polyfill` in js-reporters.

In `index.js` file, before other imports:
```js
import 'babel-polyfill'
//other imports
```

If I import `babel-polyfill` and `js-reporters` in the browser like 2 separates scripts it works.

**Comment by flore77** [comment]
@jzaefferer I didn't manage to get it work. What should we do? Should we replace all `for...of` ?

**Comment by jzaefferer** [comment]
Yes, let's replace them.

**Comment by flore77** [comment]
Or `babel` or `rollup` is breaking `babel-polyfill`,  I copied the babel-polyfill at the beginning of the js-reporters bundle without including it in the whole bundling process and everything was working. 

So another solution would be this, to change the `rollup.config.js` file to copy babel-polyfill at the beginning of the bundle, or at least the polyfill for `Symbol`.

I don't know which best. What would you prefer ?

**Comment by jzaefferer** [comment]
Any reason against using `forEach` as @leobalter suggested?

**Comment by flore77** [comment]
No, I will update. Only in the `Data.js` file i'll not use it, because there is a return statement and it is not working with forEach, and would have required other refactoring. I think that's I continued with the classical for, sorry, I will update.

**Comment by jzaefferer** [comment]
Okay.

**Comment by flore77** [comment]
Done. After this is merged, we should make another release, so this will arrive also into browserstack. Should we keep a ChangeLog ?

**Comment by jzaefferer** [comment]
Yes, let's make a patch release. You could use GitHub's Releases feature to add a note about the changes.

**Comment by flore77** [comment]
Ok, I haven't used it before, but I don't think it's so hard 😃 Then we can make the pr against browerstack.

**Pull request merged**
