### PR TITLE
Entry point

### PR DESCRIPTION
**Pull request by flore77**
@jzaefferer please review.

### CODE REVIEW

**Comment by jzaefferer** [comment]
Could you try to redo that 2nd commit, using `git mv`, so that it recognises the rename?

**Comment by flore77** [comment]
I had to broke it, in two commits, because when I was modifying the `renamed index.js` file, than `git` was seeing it like a `new file` and the` old one deleted`.

**Comment by jzaefferer** [comment]
Can you rebase it to get rid of the revert commit?

**Comment by flore77** [comment]
@jzaefferer done.

**Comment by jzaefferer** [comment]
The commit message for the first commit is a bit messy. Normally I'd just fix this while merging, in this case I think its worth if you do it yourself and pay a little more attention to those in the future ;-)

**Comment by flore77** [comment]
Yes, sorry about that.

**Comment by jzaefferer** [comment]
Alright, that's done.

**Pull request merged**
